<script lang="ts">
	import {
		Chart,
		Card,
		A,
		Button,
		Dropdown,
		DropdownItem,
		Popover,
		Tooltip
	} from 'flowbite-svelte';
	import {
		InfoCircleSolid,
		ArrowDownToBraketSolid,
		ChevronDownSolid,
		ChevronRightSolid
	} from 'flowbite-svelte-icons';

	type gs = string[];

	export let suspect: number;
	export let non_suspect: number;

	let isOpen = false;

	let total = suspect + non_suspect;

	/* const options = {
		series: [
			Math.round((suspect / total) * 100), 
			Math.round((non_suspect / total) * 100),  
			
		],
		colors: ['#F2391C', '#16CA28'],
		chart: {
			height: '380px',
			width: '100%',
			type: 'radialBar',
			sparkline: {
				enabled: true
			}
		},
		plotOptions: {
			radialBar: {
				track: {
					background: '#E5E7EB'
				},
				dataLabels: {
					show: false
				},
				hollow: {
					margin: 0,
					size: '32%'
				}
			}
		},
		grid: {
			show: false,
			strokeDashArray: 4,
			padding: {
				left: 2,
				right: 2,
				top: -23,
				bottom: -20
			}
		},
		labels: ['Suspects', 'Compliants'],
		legend: {
			show: true,
			position: 'bottom',
			fontFamily: 'Inter, sans-serif'
		},
		tooltip: {
			enabled: true,
			x: {
				show: false
			}
		},
		yaxis: {
			show: false,
			labels: {
				formatter: function (value) {
					return value + '%';
				}
			}
		}
	}; */

	const options = {
		series: [non_suspect, suspect],
		colors: ['#20F752', '#E22424'],
		chart: {
			height: 320,
			width: '100%',
			type: 'donut'
		},
		stroke: {
			colors: ['transparent'],
			lineCap: ''
		},
		plotOptions: {
			pie: {
				donut: {
					labels: {
						show: true,
						name: {
							show: true,
							fontFamily: 'Inter, sans-serif',
							offsetY: 50
						},
						total: {
							showAlways: true,
							show: true,
							label: 'Unique customers',
							fontFamily: 'Inter, sans-serif',
							formatter: function () {
								const sum = suspect + non_suspect;
								return sum;
							}
						},
						value: {
							show: true,
							fontFamily: 'Inter, sans-serif',
							offsetY: -20,
							formatter: function (value) {
								return value;
							}
						}
					},
					size: '80%'
				}
			}
		},
		grid: {
			padding: {
				top: 2
			}
		},
		labels: ['Non Suspects', 'Suspests'],
		dataLabels: {
			enabled: true
		},
		legend: {
			position: 'bottom',
			fontFamily: 'Inter, sans-serif'
		},
		yaxis: {
			labels: {
				formatter: function (value) {
					return value;
				}
			}
		},
		xaxis: {
			labels: {
				formatter: function (value) {
					return value;
				}
			},
			axisTicks: {
				show: true
			},
			axisBorder: {
				show: true
			}
		}
	};
</script>

<Card class=" p-6 min-w-full  border-none bg-gray-200 shadow-none ">
	<div class="flex w-full items-start justify-between text-gray-500">
		<div class="flex-col items-center">
			<div class="mb-1 flex items-center">
				<h5 class="me-1 text-xl font-bold leading-none dark:text-white">
					Analysis Results
				</h5>
				<InfoCircleSolid
					id="donut1"
					class="ms-1 h-3.5 w-3.5 cursor-pointer text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
				/>
				<Popover
					triggeredBy="#donut1"
					class="z-10 w-72 rounded-lg border border-gray-200 bg-white text-sm text-gray-500 shadow-sm dark:border-gray-600 dark:bg-gray-800 dark:text-gray-400"
				>
					<div class="space-y-2 p-3">
						<h3 class="font-semibold text-gray-900 dark:text-white">
							Activity growth - Incremental
						</h3>
						<p>
							Report helps navigate cumulative growth of community activities. Ideally, the chart
							should have a growing trend, as stagnating chart signifies a significant decrease of
							community activity.
						</p>
						<h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
						<p>
							For each date bucket, the all-time volume of activities is calculated. This means that
							activities in period n contain all activities up to period n, plus the activities
							generated by your community in period.
						</p>
						<A href="/">Read more <ChevronRightSolid class="ms-1.5 h-2 w-2" /></A>
					</div>
				</Popover>
			</div>
		</div>
		<div class="flex items-center justify-end">
			<ArrowDownToBraketSolid class="h-3.5 w-3.5" />
			<Tooltip>Download CSV</Tooltip>
		</div>
	</div>

	<div class="rounded-lg bg-white p-3 dark:bg-gray-700">
		<div class="mb-2 grid grid-cols-2 gap-10">
			<dl
				class="flex h-[78px] flex-col items-center justify-center rounded-lg bg-gray-200 dark:bg-gray-600"
			>
				<dt
					class="mb-1 flex h-8 w-8 items-center justify-center rounded-full bg-red-100 text-sm font-medium text-red-600 dark:bg-gray-500 dark:text-red-300"
				>
					{suspect}
				</dt>
				<dd class="text-sm font-medium text-red-600 dark:text-red-300">Suspects</dd>
			</dl>
			<dl
				class="flex h-[78px] flex-col items-center justify-center rounded-lg bg-gray-200 dark:bg-gray-600"
			>
				<dt
					class="mb-1 flex h-8 w-8 items-center justify-center rounded-full bg-green-50 text-sm font-medium text-green-600 dark:bg-gray-500 dark:text-green-300"
				>
					{non_suspect}
				</dt>
				<dd class="text-sm font-medium text-green-600 dark:text-green-300">Compliants</dd>
			</dl>
		</div>
	</div>

	<Chart {options} class="py-6" />
</Card>
